-- AlterTable
ALTER TABLE "agents" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "interactions" ALTER COLUMN "opened_at" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "closed_at" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ(6);
